export const ORDERS_FETCH_STARTED = 'ORDERS_FETCH_STARTED';
export const ORDERS_FETCH_COMPLETED = 'ORDERS_FETCH_COMPLETED';
export const ORDERS_FETCH_FAILED = 'ORDERS_FETCH_FAILED';

export const ORDER_ADD_STARTED = 'ORDER_ADD_STARTED';
export const ORDER_ADD_COMPLETED = 'ORDER_ADD_COMPLETED';
export const ORDER_ADD_FAILED = 'ORDER_ADD_FAILED';

export const ORDER_EDIT_STARTED = 'ORDER_EDIT_STARTED';
export const ORDER_EDIT_COMPLETED = 'ORDER_EDIT_COMPLETED';
export const ORDER_EDIT_FAILED = 'ORDER_EDIT_FAILED';
export const ORDER_EDIT_STATUS_STARTED = 'ORDER_EDIT_STATUS_STARTED';

export const ORDER_REMOVE_STARTED = 'ORDER_REMOVE_STARTED';
export const ORDER_REMOVE_COMPLETED = 'ORDER_REMOVE_COMPLETED';
export const ORDER_REMOVE_FAILED = 'ORDER_REMOVE_FAILED';

export const ORDER_ACTIVATED = 'ORDER_ACTIVATED';
export const ORDER_DEACTIVATED = 'ORDER_DEACTIVATED';

export const ORDER_PRODUCT_ADDED = 'ORDER_PRODUCT_ADDED';
export const ORDER_PRODUCT_EDITED = 'ORDER_PRODUCT_EDITED';
export const ORDER_PRODUCT_DELETED = 'ORDER_PRODUCT_DELETED';

export const NEW_ORDER_ACTIVATED = 'NEW_ORDER_ACTIVATED';
export const NEW_ORDER_DEACTIVATED = 'NEW_ORDER_DEACTIVATED';

export const NEW_ORDER_PRODUCT_ADDED = 'NEW_ORDER_PRODUCT_ADDED';
export const NEW_ORDER_PRODUCT_EDITED = 'NEW_ORDER_PRODUCT_EDITED';
export const NEW_ORDER_PRODUCT_DELETED = 'NEW_ORDER_PRODUCT_DELETED';

export const ORDERS_CLEARED = 'ORDERS_CLEARED';