export const RESTAURANT_SELECTED = "RESTAURANT_SELECTED";
export const RESTAURANT_DESELECTED = "RESTAURANT_DESELECTED";

export const RESTAURANT_FETCH_STARTED = "RESTAURANT_FETCH_STARTED";
export const RESTAURANT_FETCH_COMPLETED = "RESTAURANT_FETCH_COMPLETED";
export const RESTAURANT_FETCH_FAILED = "RESTAURANT_FETCH_FAILED";