export const TAG_FETCH_STARTED = 'TAG_FETCH_STARTED';
export const TAG_FETCH_COMPLETED = 'TAG_FETCH_COMPLETED';
export const TAG_FETCH_FAILED = 'TAG_FETCH_FAILED';

export const TAG_ADD_STARTED = 'TAG_ADD_STARTED';
export const TAG_ADD_COMPLETED = 'TAG_ADD_COMPLETED';
export const TAG_ADD_FAILED = 'TAG_ADD_FAILED';

export const TAG_REMOVE_STARTED = 'TAG_REMOVE_STARTED';
export const TAG_REMOVE_COMPLETED = 'TAG_REMOVE_COMPLETED';
export const TAG_REMOVE_FAILED = 'TAG_REMOVE_FAILED';

export const TAG_SELECTED = 'TAG_SELECTED';